---

- name: set hostname
  hostname: 
    name: '{{ hostname }}'

- name: download zabbix repo
  get_url: 
    url: https://repo.zabbix.com/zabbix/4.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.2-3%2Bbionic_all.deb
    dest: /tmp/zabbix_repo.deb
    mode: 0755

- name: install zabbix repo
  shell: dpkg -i /tmp/zabbix_repo.deb

- name: update repo
  apt: update_cache=yes

- name: install packages
  apt:
    state: present
    name:
     - python-simplejson
     - apache2 
     - libapache2-mod-php
     - mysql-server
     - php 
     - php-mbstring 
     - php-gd 
     - php-xml 
     - php-bcmath 
     - php-ldap 
     - php-mysql
     - zabbix-server-mysql 
     - zabbix-frontend-php 
     - zabbix-agent
     - python-mysqldb
     - python3-pip
  tags: packages 

- name: Install pymysql
  shell: pip3 install pymysql

- name: setting timezone for php
  template:
   src: php.ini
   dest: /etc/php/7.2/apache2/php.ini

- name: Create zabbix database
  mysql_db: 
    name: '{{ zabbix_db_name }}'
    state: present
    collation: utf8_bin
    encoding: utf8
  tags: db


- name: Create zabbix dabatase user
  mysql_user: name={{ zabbix_db_user }} password={{ zabbix_db_password }} priv={{ zabbix_db_name }}.*:ALL host='localhost' state=present
  no_log: True
  tags: db

- name: loading zabbix db schema
  mysql_db: 
    name: "{{ zabbix_db_name }}"
    state: import
    target: /usr/share/doc/zabbix-server-mysql/create.sql.gz
    
- name: edit zabbix conf file
  template:
    dest: /etc/zabbix/zabix_server.conf
    src: zabbix_server.conf
  notify:
   - restart-services

- name: install apache config for zabbix-frontend
  copy: 
    src: /etc/zabbix/apache.conf 
    dest: /etc/apache2/sites-available/000-default.conf
    remote_src: yes
  notify: reload_apache
  tags: apache

- name: restart zabbix
  service:
    state: restarted
    name: zabbix-server
    enabled: yes
